# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel
repos:
  CRAN: https://cloud.r-project.org
sudo: false
cache: packages
env:
  - LINTR_COMMENT_BOT=false
r_github_packages:
  - jimhester/lintr
script:
  - R -f tests/render_rmds.R
